all:
	g++ arrays.cpp -O0 -o arrays-O0.out
	g++ arrays.cpp -O2 -o arrays-O2.out
	g++ fft.cpp -O0 -o fft-O0.out
	g++ fft.cpp -O2 -o fft-O2.out
	g++ lesscorrelated.cpp -O0 -o lesscorrelated-O0.out
	g++ lesscorrelated.cpp -O2 -o lesscorrelated-O2.out

clean:
	rm *.out
